In [21]:
# Import the necessary modules and libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn import metrics
from sklearn.metrics import r2_score
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler


In [22]:
df_test = pd.read_csv('test_v1.csv', sep = ';',decimal =',')
df_train = pd.read_csv('train_v1.csv', sep = ';', decimal =',')

In [23]:
X_train = df_train.drop(columns = ['Disintegration_Time'])
y_train = df_train[['Disintegration_Time']]

X_test = df_test.drop(columns = ['Disintegration_Time'])
y_test = df_test[['Disintegration_Time']]

In [24]:
scaler = StandardScaler()
# fit scaler to training data set, then transform both data sets (training and testing)
scaler.fit(X_train) 
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [25]:
X_train

array([[-2.00409417,  2.00409417,  1.940285  , -1.940285  , -2.23606798,
        -2.00409417, -2.00409417, -2.01399597],
       [-2.00409417,  2.00409417,  1.940285  , -1.940285  , -2.23606798,
        -2.00409417, -2.00409417, -2.01399597],
       [-2.00409417,  2.00409417,  1.940285  , -1.940285  , -2.23606798,
        -2.00409417, -2.00409417, -2.01399597],
       [-2.00409417,  2.00409417,  1.940285  , -1.940285  , -2.23606798,
        -2.00409417, -2.00409417, -2.01399597],
       [-2.00409417,  2.00409417,  1.940285  , -1.940285  , -2.23606798,
        -2.00409417, -2.00409417, -2.01399597],
       [-2.00409417,  2.00409417,  1.940285  , -1.940285  , -2.23606798,
        -2.00409417, -2.00409417, -2.01399597],
       [-0.28629917,  0.28629917,  0.48507125, -0.48507125,  0.4472136 ,
        -0.28629917, -0.28629917, -0.10599979],
       [-0.28629917,  0.28629917,  0.48507125, -0.48507125,  0.4472136 ,
        -0.28629917, -0.28629917, -0.10599979],
       [-0.28629917,  0.28629917

In [26]:
#data_train[data_train.notnull()]

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.3, random_state=0)

In [28]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(25, 8) (25, 1) (11, 8) (11, 1)


In [29]:

model = LinearRegression().fit(X_train,y_train)
y_pred = model.predict(X_test)
print(y_pred)
#print(mean_squared_error(y_test,y_pred))

[[27.25566667]
 [20.27166667]
 [13.323     ]
 [27.25566667]
 [20.27166667]
 [13.323     ]
 [13.28766667]
 [ 8.156     ]
 [13.28766667]
 [20.307     ]
 [20.307     ]]


In [30]:
mlr = LinearRegression()

In [31]:
mlr.fit(X_train, y_train)

LinearRegression()

In [32]:
mlr.intercept_

array([17.10016667])

In [33]:

print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))


Root Mean Squared Error: 1.3159199800669468
